#!/usr/bin/env ruby

require 'bundler/setup'

$LOAD_PATH << File.expand_path('../lib', __dir__)

require 'async'
require 'stiction'

Async do
  Stiction.watch(trace: true)

  loop do
    i = 0
    25000.times do
      i += 1
    end
  end
end
